version: "3.9"
services:
  nginx:
    build:
      context: .
      target: nginx
    container_name: nginx
    image: nginx:artist
    ports:
      - "80:80"
    networks:
      - nginx
  vue:
    build:
      context: .
      target: vue
    container_name: vue
    image: vue:artist
    networks:
      - vue
      - nginx

networks:
  nginx:

  vue:

