version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:milad
    ports:
      - "80:80"
    networks:
      - nginx
  vue:
    container_name: vue
    image: vue:milad
    networks:
      - vue
      - nginx

networks:
  nginx:

  vue:

