version: "3.9"
services: 
  vue:
    image: vue:milad
    networks: 
      - vue_nginx
networks: 
  vue_nginx:
    external: true


    # docker network connect vuejs_default nginx_nginx_1
    #docker network connect nginx_default vuejs_vue_1